### PR TITLE
fix: Added dropdown for enum selection

### PR DESCRIPTION
**Pull request by mahatoankitkumar**
## Problem
Add dropdown for enum selection

## Solution
Added dropdown for enum selection

https://github.com/juspay/superposition/assets/79959102/b59e138b-96e3-4e25-8e60-300de01d8ffd

### CODE REVIEW

**Comment by Datron** [comment]
@mahatoankitkumar can you add a video for dimensions too?

**Comment by knutties** [comment]
@mahatoankitkumar - in the default config key addition section, the choose enum section show ideally go below the section where you configure the list of enums right ?  That is the natural order I believe.

What do you think?

**Comment by mahatoankitkumar** [comment]
> @mahatoankitkumar - in the default config key addition section, the choose enum section show ideally go below the section where you configure the list of enums right ? That is the natural order I believe.
> 
> What do you think?

makes sense.

**Comment by Datron** [comment]
@mahatoankitkumar can you include the video in overrides screen? An field thats an enum should just be a dropdown

**Pull request closed without merging**
